name: rumenbalev exam CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install deps
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Show my SoftUni username
      run: echo "@rumenbalev"
      
